apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-api-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: todo-api
  endpoints:
  - port: http
    path: /metrics